In [1]:
#Importing the modules
import pandas as pd
import numpy as np


from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
from pandas import DataFrame


from matplotlib import pyplot as plt
import seaborn as sns
import sklearn.metrics as metrics
import pickle

import shap

In [2]:
dados = pd.read_csv('Predicao_energia.csv', sep=';')
dados.head()

L_501     L_503    L_511C  L_511R     L_512  L_521    L_551    L_561  \
0     0.00     0.000  2384.407     0.0  3020.924    0.0    0.000     0.00   
1     0.00     0.000  1621.611     0.0  6076.104  170.8    0.000  2640.00   
2  1407.75  2241.603  2118.966     0.0  2748.683  623.9  202.032  3868.92   
3  2804.25  2814.027  3680.043     0.0  3817.594   35.4    0.000   271.20   
4  3393.75     0.000  4069.322     0.0  6866.077    0.0    0.000  1642.08   

     L_562  Trasfega  Filtracao  Brassagem    Energia  
0     0.00     10397    14865.0    17563.8  102784.59  
1     0.00     12859     3640.0    13985.4  115752.86  
2   441.96     11091    11693.0    12221.7  139420.40  
3  1186.14      6238        0.0    14022.1  130246.60  
4   797.52      3204    12852.0    12318.0  125788.40

In [3]:
#Verificando a existência de valores nulos
dados.isna().sum()

L_501        0
L_503        0
L_511C       0
L_511R       0
L_512        0
L_521        0
L_551        0
L_561        0
L_562        0
Trasfega     0
Filtracao    0
Brassagem    0
Energia      0
dtype: int64

In [4]:
#Normalizando os dados
from sklearn.preprocessing import Normalizer
values = Normalizer().fit_transform(dados.values)
print(values)

[[0.         0.         0.02251341 ... 0.14035434 0.16583623 0.97048527]
 [0.         0.         0.01379434 ... 0.03096391 0.11896775 0.98465952]
 [0.00998384 0.01589757 0.01502783 ... 0.08292741 0.08667698 0.98877727]
 ...
 [0.         0.02357719 0.04225035 ... 0.17001851 0.09790136 0.97331049]
 [0.         0.         0.0375339  ... 0.11630662 0.15238001 0.97184506]
 [0.         0.01121641 0.03738717 ... 0.1131392  0.         0.9899817 ]]


### Para avaliar se a clusterização é boa, temos algumas métricas de avalição:
O coefieciente de Silhouette varia de -1 a 1, quanto mais mais perto de 1 mais coeso e denso. 